### ISSUE TITLE
Bluemaps-Plugin-Loading/ERROR 

### ISSUE THREAD

**Issue by mechwarrior11** [BlueMap-Minecraft/BlueMap#468]
### What i did / Steps to reproduce

I have a fabric server that I made yesterday with a large modpack, it has a 5k block radius progenerated, I added bluemaps to the mods folder and followed the steps for the installation process, but bluemaps fails to load and I get this message at server startup, and when using /bluemaps reload. I do not see anywhere saying "Webserver Started" or anything similar in the logs either, not sure what could be going on here. Any help? 

[Logfile.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/12373360/Logfile.txt)
```
[15:26:55] [BlueMap-Plugin-Loading/INFO]: Loading BlueMap...
[15:26:55] [BlueMap-Plugin-Loading/ERROR]: Uncaught exception in thread "BlueMap-Plugin-Loading"
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_6489.method_48018()'
	at de.bluecolored.bluemap.fabric.FabricMod.getMinecraftVersion(FabricMod.java:130) ~[BlueMap-3.16-fabric-1.19.4.jar:?]
	at de.bluecolored.bluemap.common.BlueMapService.getResourcePack(BlueMapService.java:336) ~[BlueMap-3.16-fabric-1.19.4.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:154) ~[BlueMap-3.16-fabric-1.19.4.jar:?]
	at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[BlueMap-3.16-fabric-1.19.4.jar:?]
	at de.bluecolored.bluemap.fabric.FabricMod.lambda$onInitialize$2(FabricMod.java:105) ~[BlueMap-3.16-fabric-1.19.4.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Versions
`fabric version 0.14.22 - mc version 1.19.2`
`BlueMap-3.16-fabric-1.19.4.jar` is the jar used 

Oh the biomes you go is on the server - might be important to know? 
Linux - Ubuntu desktop 

Thank you in advance

**Comment by TBlueF** [comment]
BlueMap 3.16 has no version for fabric 1.19.2, the version you used only works on fabric 1.19.4 ... 

The latest version of BlueMap that supports fabric 1.19.2 is [3.13](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v3.13)

**Comment by TechnicJelle** [comment]
I believe Minecraft 1.19.4 is drastically different under the hood from 1.19.2, and BlueMap only supports the latest minor version of each major Minecraft version, so it's incompatible...
The last BlueMap version that supported 1.19.2 was [BlueMap 3.13](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v3.13)

**Comment by mechwarrior11** [comment]
*head smashing sound* ofc its as simple as that 
Thank you both, I've had a long day lmao
